name: Test

on:
  push:
    branches: ["**"]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'LICENSE'
  pull_request:
    branches: ["**"]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'LICENSE'

# 并发控制
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-test
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  # 启动 Oracle 服务
  setup-oracle:
    runs-on: ubuntu-latest
    services:
      oracle:
        image: gvenzl/oracle-xe:21-slim
        env:
          ORACLE_PASSWORD: oracle
          APP_USER: test
          APP_USER_PASSWORD: test123
        ports:
          - 1521:1521
        options: >-
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    
    # 设置 TCP 代理
    steps:
      - name: Set up TCP proxy
        run: |
          sudo apt-get update
          sudo apt-get install -y socat
          sudo socat TCP-LISTEN:1521,fork TCP:localhost:1521 &
      
      - name: Wait for Oracle
        run: |
          timeout 300 bash -c 'until echo > /dev/tcp/localhost/1521; do sleep 1; done'
          sleep 30 # 额外等待以确保服务完全就绪

  # 多平台测试
  test:
    needs: setup-oracle
    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.22', '1.23']
        os: [ubuntu-latest, windows-latest, macos-latest]
        exclude:
          - os: windows-latest
            go-version: '1.23'
          - os: macos-latest
            go-version: '1.23'
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      # Linux 特定步骤
      - name: Restore Oracle Instant Client (Linux)
        if: matrix.os == 'ubuntu-latest'
        id: cache-oracle-linux
        uses: actions/cache/restore@v4
        with:
          path: /opt/oracle/instantclient_21_9
          key: ubuntu-22.04-oracle-instantclient-${{ hashFiles('**/go.sum') }}
          restore-keys: ubuntu-22.04-oracle-instantclient-
      
      - name: Install Oracle Instant Client (Linux)
        if: matrix.os == 'ubuntu-latest' && steps.cache-oracle-linux.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y libaio1
          
          wget https://download.oracle.com/otn_software/linux/instantclient/219000/instantclient-basic-linux.x64-21.9.0.0.0dbru.zip
          sudo mkdir -p /opt/oracle
          sudo unzip instantclient-basic-linux.x64-21.9.0.0.0dbru.zip -d /opt/oracle
          sudo mkdir -p /opt/oracle/instantclient_21_9/network/admin
          echo "XE =
            (DESCRIPTION =
            (ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 1521))
            (CONNECT_DATA =
              (SERVER = DEDICATED)
              (SERVICE_NAME = FREEPDB1)
            )
          )" | sudo tee /opt/oracle/instantclient_21_9/network/admin/tnsnames.ora
          
      - name: Configure Oracle Instant Client (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "/opt/oracle/instantclient_21_9" | sudo tee /etc/ld.so.conf.d/oracle-instantclient.conf
          sudo ldconfig
          
          echo "LD_LIBRARY_PATH=/opt/oracle/instantclient_21_9:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "PATH=/opt/oracle/instantclient_21_9:$PATH" >> $GITHUB_ENV
      
      - name: Cache Oracle Instant Client (Linux)
        if: matrix.os == 'ubuntu-latest' && steps.cache-oracle-linux.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: /opt/oracle/instantclient_21_9
          key: ubuntu-22.04-oracle-instantclient-${{ hashFiles('**/go.sum') }}
          restore-keys: ubuntu-22.04-oracle-instantclient-

      # Windows 特定步骤
      - name: Install Oracle Instant Client (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          $InstantClientVersion = "21.9.0.0.0"
          $InstantClientURL = "https://download.oracle.com/otn_software/nt/instantclient/219000/instantclient-basic-windows.x64-21.9.0.0.0dbru.zip"
          
          Invoke-WebRequest -Uri $InstantClientURL -OutFile instantclient.zip
          Expand-Archive instantclient.zip -DestinationPath C:\oracle
          
          mkdir C:\oracle\instantclient_21_9\network\admin
          @"
          XE =
            (DESCRIPTION =
            (ADDRESS = (PROTOCOL = TCP)(HOST = oracle)(PORT = 1521))
            (CONNECT_DATA =
              (SERVER = DEDICATED)
              (SERVICE_NAME = FREEPDB1)
            )
          )
          "@ | Out-File C:\oracle\instantclient_21_9\network\admin\tnsnames.ora -Encoding ASCII
          
          echo "C:\oracle\instantclient_21_9" | Out-File -FilePath $env:GITHUB_PATH -Append
          echo "PATH=C:\oracle\instantclient_21_9;$env:PATH" >> $env:GITHUB_ENV

      # macOS 特定步骤
      - name: Install Oracle Instant Client (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install instantclient-basic
          mkdir -p $(brew --prefix instantclient-basic)/lib/network/admin
          echo "XE =
            (DESCRIPTION =
            (ADDRESS = (PROTOCOL = TCP)(HOST = oracle)(PORT = 1521))
            (CONNECT_DATA =
              (SERVER = DEDICATED)
              (SERVICE_NAME = FREEPDB1)
            )
          )" > $(brew --prefix instantclient-basic)/lib/network/admin/tnsnames.ora
          
          echo "DYLD_LIBRARY_PATH=$(brew --prefix instantclient-basic)/lib:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "PATH=$(brew --prefix instantclient-basic)/bin:$PATH" >> $GITHUB_ENV

      # 设置 hosts 文件
      - name: Setup hosts file (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          Add-Content -Path $env:windir\System32\drivers\etc\hosts -Value "oracle 127.0.0.1"

      - name: Setup hosts file (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          echo "127.0.0.1 oracle" | sudo tee -a /etc/hosts

      - name: Create test config
        shell: bash
        run: |
          cat > config.json << EOF
          {
            "databases": {
              "test": {
                "name": "测试库",
                "user": "system",
                "password": "oracle",
                "host": "oracle",
                "port": 1521,
                "service": "FREEPDB1"
              }
            },
            "max_retries": 3,
            "max_concurrent": 1,
            "batch_size": 1000,
            "timeout": 30,
            "log_level": "debug",
            "log_file": "logs/sql-runner.log"
          }
          EOF

      # 运行测试
      - name: Run unit tests
        run: go test -v -race -coverprofile=coverage.unit.txt ./cmd/... ./pkg/... ./internal/...

      # 合并覆盖率报告
      - name: Combine coverage reports
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "mode: atomic" > coverage.txt
          tail -n +2 coverage.unit.txt >> coverage.txt

      # 上传覆盖率报告
      - name: Upload test coverage
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          flags: ${{ matrix.os }}-go${{ matrix.go-version }}

  # 测试结果汇总
  test-results:
    if: always()
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check test results
        run: |
          if [ "${{ needs.test.result }}" = "success" ]; then
            echo "All tests passed successfully!"
            exit 0
          else
            echo "Some tests failed!"
            exit 1
          fi
