name: Test

on:
  push:
    branches: ["**"]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'LICENSE'
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      oracle:
        image: gvenzl/oracle-xe:21-slim
        env:
          ORACLE_PASSWORD: oracle
          APP_USER: test
          APP_USER_PASSWORD: test123
        ports:
          - 1521:1521
        options: >-
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: true
      
      - name: Install Oracle Instant Client
        run: |
          # 安装依赖
          sudo apt-get update
          sudo apt-get install -y libaio1
          
          # 下载并解压 Basic 包
          wget https://download.oracle.com/otn_software/linux/instantclient/219000/instantclient-basic-linux.x64-21.9.0.0.0dbru.zip
          sudo mkdir -p /opt/oracle
          sudo unzip instantclient-basic-linux.x64-21.9.0.0.0dbru.zip -d /opt/oracle
          
          # 配置环境变量
          echo "/opt/oracle/instantclient_21_9" | sudo tee /etc/ld.so.conf.d/oracle-instantclient.conf
          sudo ldconfig
          
          echo "export LD_LIBRARY_PATH=/opt/oracle/instantclient_21_9:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "export PATH=/opt/oracle/instantclient_21_9:$PATH" >> $GITHUB_ENV
          
          # 创建 TNS 配置
          sudo mkdir -p /opt/oracle/instantclient_21_9/network/admin
          echo "XE =
            (DESCRIPTION =
              (ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 1521))
              (CONNECT_DATA =
                (SERVER = DEDICATED)
                (SERVICE_NAME = FREEPDB1)
              )
            )" | sudo tee /opt/oracle/instantclient_21_9/network/admin/tnsnames.ora

      - name: Create test config
        run: |
          cat > config.json << EOF
          {
            "databases": {
              "test": {
                "name": "测试库",
                "user": "system",
                "password": "oracle",
                "host": "localhost",
                "port": 1521,
                "service": "FREEPDB1"
              }
            },
            "max_retries": 3,
            "max_concurrent": 1,
            "batch_size": 1000,
            "timeout": 30,
            "log_level": "debug"
          }
          EOF

      - name: Run unit tests
        run: go test -v -coverprofile=coverage.unit.txt ./pkg/... ./internal/...

      - name: Run integration tests
        run: |
          source $GITHUB_ENV
          go test -v -coverprofile=coverage.integration.txt ./test/integration/...

      - name: Run full tests
        run: |
          source $GITHUB_ENV
          go test -v -coverprofile=coverage.full.txt ./...

      - name: Combine coverage reports
        run: |
          echo "mode: atomic" > coverage.txt
          tail -n +2 coverage.unit.txt >> coverage.txt
          tail -n +2 coverage.integration.txt >> coverage.txt
          tail -n +2 coverage.full.txt >> coverage.txt

      - name: Upload test coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
